name: publish
on:
  push:
    branches: master
jobs:
  manual:
    name: "Generate and distribute page"
    runs-on: ubuntu-latest
    steps:
      - name: Install jekyll
        uses: magit/actions/install-jekyll@main
      - name: Generate page
        uses: magit/actions/page-generate@main
      - name: Publish page
        uses: magit/actions/page-publish@main
        with:
          key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
